-- ============================================================
-- منجزات الشباب السعودي — الجداول والمحتوى (سكيمة DATA_CENTER)
-- يُشغَّل مرة واحدة في SQL Workshop → SQL Scripts
-- ============================================================

CREATE TABLE "ACHIEVEMENT_CATEGORIES" (
  "CODE"          VARCHAR2(40) NOT NULL,
  "NAME_AR"       VARCHAR2(200) NOT NULL,
  "ICON"          VARCHAR2(60),
  "COLOR"         VARCHAR2(20),
  "DISPLAY_ORDER" NUMBER DEFAULT 100,
  CONSTRAINT "ACH_CAT_PK" PRIMARY KEY ("CODE")
);

CREATE TABLE "YOUTH_ACHIEVEMENTS" (
  "ID"            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "YEAR_NO"       NUMBER DEFAULT 2025 NOT NULL,
  "CATEGORY"      VARCHAR2(40) NOT NULL,
  "TITLE"         VARCHAR2(500) NOT NULL,
  "SUMMARY"       VARCHAR2(4000),
  "FIGURE_VALUE"  VARCHAR2(50),      -- الرقم البارز (يظهر في شريط الأرقام)
  "FIGURE_LABEL"  VARCHAR2(200),     -- وصف الرقم
  "SOURCE_URL"    VARCHAR2(1000),
  "IS_FEATURED"   NUMBER(1) DEFAULT 0,   -- 1 = يظهر في الصفحة الرئيسية
  "DISPLAY_ORDER" NUMBER DEFAULT 100,
  "IS_PUBLISHED"  NUMBER(1) DEFAULT 1,
  "CREATED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT "ACH_PK" PRIMARY KEY ("ID"),
  CONSTRAINT "ACH_CAT_FK" FOREIGN KEY ("CATEGORY") REFERENCES "ACHIEVEMENT_CATEGORIES"("CODE")
);

CREATE INDEX "ACH_YEAR_CAT_IX" ON "YOUTH_ACHIEVEMENTS" ("YEAR_NO","CATEGORY","IS_PUBLISHED");

-- ---------------- التصنيفات ----------------
INSERT INTO "ACHIEVEMENT_CATEGORIES" VALUES ('international','المشاركات الدولية','Globe','#1e5f8f',10);
INSERT INTO "ACHIEVEMENT_CATEGORIES" VALUES ('local','المشاركات المحلية والتطوع','HeartHandshake','#1f7a6c',20);
INSERT INTO "ACHIEVEMENT_CATEGORIES" VALUES ('awards','الجوائز العالمية','Trophy','#96774f',30);
INSERT INTO "ACHIEVEMENT_CATEGORIES" VALUES ('patents','براءات الاختراع','Lightbulb','#8a5a2b',40);
INSERT INTO "ACHIEVEMENT_CATEGORIES" VALUES ('scholars','إنجازات المبتعثين','GraduationCap','#4a4a8f',50);
INSERT INTO "ACHIEVEMENT_CATEGORIES" VALUES ('sports','الإنجازات الرياضية','Medal','#1d6b45',60);
INSERT INTO "ACHIEVEMENT_CATEGORIES" VALUES ('business','ريادة الأعمال','Rocket','#a1421f',70);
INSERT INTO "ACHIEVEMENT_CATEGORIES" VALUES ('initiatives','مبادرات التمكين','Sparkles','#1e2a52',80);
INSERT INTO "ACHIEVEMENT_CATEGORIES" VALUES ('nonprofit','إسهام القطاع غير الربحي','Building2','#5b4a7a',90);

-- ---------------- المشاركات الدولية ----------------
INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('international','مشاركة الشباب السعودي في القمة العالمية للشباب 2025',
 'شارك وفد المملكة بقيادة هيئة الاتصالات والفضاء والتقنية في جلسات حوارية تناولت أولويات الشباب والتمكين الرقمي للمرأة القيادية واستكشافات الذكاء الاصطناعي، ضمن مبادرة «توصيل الجيل».',0,10);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('international','منتدى الشباب التابع للمجلس الاقتصادي والاجتماعي للأمم المتحدة (ECOSOC) 2025',
 'شارك وفد سعودي في مقر الأمم المتحدة بنيويورك بدعم من مؤسسة «مسك» ضمن برنامج «أصوات عالمية»، وناقش قضايا الاستدامة والابتكار وتعزيز التعاون بين القطاعات.',1,20);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","FIGURE_VALUE","FIGURE_LABEL","IS_FEATURED","DISPLAY_ORDER") VALUES
('international','مشاركة الكشافة السعودية في الحدث الكشفي العالمي JOTA-JOTI 2025',
 'مشاركة جمعية الكشافة العربية السعودية في أكبر حدث كشفي رقمي تحت شعار «عالم يشكله الشباب»، بمشاركة أكثر من مليوني شاب من أكثر من 170 دولة.',
 '170+','دولة مشاركة في الحدث الكشفي',0,30);

-- ---------------- المشاركات المحلية والتطوع ----------------
INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","FIGURE_VALUE","FIGURE_LABEL","IS_FEATURED","DISPLAY_ORDER") VALUES
('local','التطوع الشبابي في المملكة',
 'سجّل المركز الوطني لتنمية القطاع غير الربحي مشاركة 462 ألف متطوع أسهموا بـ56 مليون ساعة تطوعية خلال ثلاثة أشهر، في مؤشر على اتساع العمل التطوعي بين الشباب.',
 '56 مليون','ساعة تطوعية خلال 3 أشهر',1,10);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","FIGURE_VALUE","FIGURE_LABEL","IS_FEATURED","DISPLAY_ORDER") VALUES
('local','تطوع الشباب في خدمة ضيوف الرحمن',
 'أسهم الشباب في خدمة أكثر من 1.6 مليون حاج بـ2.1 مليون ساعة تطوعية في حج 1446هـ، بمشاركة 420 ألف مشتغل في المنظومة.',
 '2.1 مليون','ساعة تطوعية في الحج',1,20);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","FIGURE_VALUE","FIGURE_LABEL","IS_FEATURED","DISPLAY_ORDER") VALUES
('local','حملة «كلّي فخر» للتطوع الصحي',
 'أطلق مركز التطوع الصحي بوزارة الصحة حملة تحتفي بـ700 ألف متطوع صحي قدّموا 55,319,222 ساعة تطوعية بقيمة اقتصادية بديلة تجاوزت 3.9 مليار ريال، ضمن مستهدف رؤية 2030 للوصول إلى مليون متطوع.',
 '700 ألف','متطوع صحي',0,30);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('local','برنامج «تحدي نحو الأثر» من «مسك» و«غيتس»',
 'شراكة بين مؤسسة محمد بن سلمان «مسك» ومؤسسة غيتس لتمكين الشباب السعودي من قيادة حلول تنموية ذات أثر عالمي.',0,40);

-- ---------------- الجوائز العالمية ----------------
INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","FIGURE_VALUE","FIGURE_LABEL","IS_FEATURED","DISPLAY_ORDER") VALUES
('awards','23 جائزة للمنتخب السعودي في «آيسف 2025»',
 'حصد المنتخب السعودي للعلوم والهندسة 23 جائزة في معرض ريجينيرون الدولي للعلوم والهندسة بمدينة كولومبوس الأمريكية، بمشاركة أكثر من 1700 طالب من 70 دولة — منها 14 جائزة كبرى و9 جوائز خاصة.',
 '23','جائزة دولية في آيسف 2025',1,10);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","FIGURE_VALUE","FIGURE_LABEL","IS_FEATURED","DISPLAY_ORDER") VALUES
('awards','6 جوائز في أولمبياد الرياضيات الدولي',
 'حقق الفريق السعودي في النسخة الـ66 بأستراليا 3 ميداليات برونزية و3 شهادات تقدير، بمشاركة 630 طالبًا من 110 دول — ليرتفع رصيد المملكة إلى 12 فضية و48 برونزية و22 شهادة تقدير.',
 '6','جوائز في أولمبياد الرياضيات',1,20);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('awards','ميدالية برونزية في أولمبياد المعلوماتية الأوروبي للبنات',
 'نالت الطالبة ريفال الحازمي من تعليم تبوك ميدالية برونزية في النسخة الخامسة بمدينة بون الألمانية بمشاركة 226 طالبة من 60 دولة، ليصل رصيد المملكة إلى 7 جوائز دولية في هذه المسابقة.',0,30);

-- ---------------- براءات الاختراع ----------------
INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","FIGURE_VALUE","FIGURE_LABEL","IS_FEATURED","DISPLAY_ORDER") VALUES
('patents','4,355 براءة اختراع صادرة في عام واحد',
 'أعلنت الهيئة السعودية للملكية الفكرية إصدار 4,355 براءة اختراع وإيداع 8,029 طلبًا بنمو 13.3%، مع إصدار براءة الاختراع رقم 20,000 في منتصف 2025 وصعود المملكة إلى المركز الـ40 عالميًا في مؤشرات الابتكار.',
 '4,355','براءة اختراع صادرة',1,10);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","FIGURE_VALUE","FIGURE_LABEL","IS_FEATURED","DISPLAY_ORDER") VALUES
('patents','8,029 طلب براءة اختراع بنمو 13.3%',
 'ارتفاع طلبات براءات الاختراع المودعة إلى 8,029 طلبًا، إلى جانب 1,578 شهادة نماذج صناعية بنمو 8.7%، و1,504 عمل أدبي بنمو 63.1%.',
 '13.3%','نمو طلبات براءات الاختراع',0,20);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('patents','براءة اختراع «جهاز ترشيد استهلاك المياه»',
 'منحت الهيئة السعودية للملكية الفكرية براءة اختراع للمهندسَين منصور المزيرعي ورائد الخلف لجهاز إلكتروني يرصد استهلاك المياه ويتحكم فيه بتقنية التحليل اللحظي متعدد المصادر، دعمًا لمستهدفات رؤية 2030 في ترشيد المياه.',0,30);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('patents','ميدالية ذهبية وجائزة خاصة في معرض Euroinvent 2025',
 'حقق المخترعان مريم عطيف وعلي مجممي الميدالية الذهبية وجائزة خاصة في المعرض الدولي بمدينة ياش برومانيا عن اختراع «ساعة فراس الصحية الذكية للأطفال».',0,40);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('patents','الجائزة الكبرى كأفضل مخترع في آسيا 2025',
 'حصد الباحث عبدالله المزيعل من جامعة الملك خالد الجائزة الكبرى كأفضل مخترع في آسيا خلال معرض ITEX الدولي بماليزيا، وصُنّف ضمن أفضل 1% من العلماء عالميًا.',1,50);

-- ---------------- إنجازات المبتعثين ----------------
INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('scholars','اكتشاف طبي سعودي لطفرتين وراثيتين لأمراض القلب',
 'نجح المبتعث نايف المنتشري من جامعة طيبة في كندا في اكتشاف طفرتين وراثيتين تصيبان حاملهما بأمراض القلب التاجية، ونال اكتشافه اعترافًا دوليًا من كبرى المؤسسات البحثية في كندا والولايات المتحدة.',1,10);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('scholars','جائزة أفضل مشروع بحثي طبي في كندا',
 'فاز الدكتور سليمان المسهر، المبتعث لدراسة أمراض الجهاز الهضمي، بجائزة أفضل مشروع بحثي بين أطباء الباطنية المقيمين في جامعة ماكغيل.',0,20);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","FIGURE_VALUE","FIGURE_LABEL","IS_FEATURED","DISPLAY_ORDER") VALUES
('scholars','أكثر من 110,000 طالب دراسات عليا',
 'تجاوز عدد طلاب الماجستير والدكتوراه في المملكة 110,000 طالب وطالبة، مع إنتاج آلاف الرسائل العلمية سنويًا — وسجّلت جامعة الملك عبدالعزيز وحدها أكثر من 21,000 ورقة بحثية منشورة خلال 2022–2024.',
 '110,000+','طالب دراسات عليا',1,30);

-- ---------------- الإنجازات الرياضية ----------------
INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('sports','تأهل المنتخب السعودي إلى نهائيات كأس العالم 2026',
 'تأهل المنتخب السعودي الأول لكرة القدم إلى نهائيات كأس العالم 2026، إلى جانب تأهل منتخب الناشئين لكرة اليد إلى كأس العالم 2025، وفوز الهلال على بطل أوروبا مانشستر سيتي كأول فريق عربي وآسيوي.',1,10);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","FIGURE_VALUE","FIGURE_LABEL","IS_FEATURED","DISPLAY_ORDER") VALUES
('sports','كأس العالم للرياضات الإلكترونية في نسختها الأولى',
 'استضافت المملكة بطولة كأس العالم للرياضات الإلكترونية بمشاركة أكثر من 2,500 لاعب عالمي، وتوّج فريق «فالكونز» السعودي باللقب.',
 '2,500+','لاعب عالمي في كأس العالم للرياضات الإلكترونية',0,20);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","FIGURE_VALUE","FIGURE_LABEL","IS_FEATURED","DISPLAY_ORDER") VALUES
('sports','70 ميدالية للرياضيين السعوديين',
 'حصد الرياضيون السعوديون 15 ميدالية ذهبية و23 فضية و32 برونزية في مختلف الرياضات، إضافة إلى فوز سالم الدوسري بلقب أفضل لاعب في آسيا وتحقيق الأهلي كأس نخبة آسيا.',
 '70','ميدالية في مختلف الرياضات',1,30);

-- ---------------- ريادة الأعمال ----------------
INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","FIGURE_VALUE","FIGURE_LABEL","IS_FEATURED","DISPLAY_ORDER") VALUES
('business','6 شركات سعودية في نهائيات كأس العالم لريادة الأعمال (بيبان 2025)',
 'تأهلت ست شركات ناشئة سعودية: SARsatX لتكنولوجيا الفضاء · Expanse Cosmos لاقتصاد الفضاء الجديد · Thrivve للتقنية المالية والتنقل · ADADK لإمدادات المياه والحلول البيئية · EcoPallets لتحويل سعف النخيل إلى منصات شحن · iRAMA للزراعة المائية الذكية.',
 '6','شركات سعودية في نهائيات بيبان',1,10);

-- ---------------- مبادرات التمكين ----------------
INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","FIGURE_VALUE","FIGURE_LABEL","IS_FEATURED","DISPLAY_ORDER") VALUES
('initiatives','مبادرة «مليون سعودي للذكاء الاصطناعي» (سماي)',
 'تهدف إلى تمكين مليون شاب وشابة بمهارات الذكاء الاصطناعي ورفع الوعي به وتفعيل تطبيقاته، لتجهيز الشباب لقيادة التحول التقني ومواكبة متطلبات سوق العمل العالمي.',
 'مليون','مستهدف تمكينهم في الذكاء الاصطناعي',1,10);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('initiatives','برامج «مسك» النوعية',
 'تشمل برنامج القادة (زمالات ومسارات قيادية بالتعاون مع أفضل الجامعات العالمية)، ومسرّعات وحاضنات الأعمال مثل «مسك الانطلاق» و«سبارك» لتحويل أفكار الشباب الريادية إلى مشاريع قابلة للتنفيذ.',0,20);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('initiatives','برنامج تطوير الخريجين «تمهير»',
 'تدريب على رأس العمل للخريجين السعوديين من الجامعات المحلية والخارجية في المؤسسات الحكومية والشركات المتميزة لاكتساب الخبرة العملية.',0,30);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('initiatives','تمويل العمل الحر «نفاذ»',
 'تسهيلات تمويلية ميسّرة للراغبين في بدء أعمالهم الخاصة أو الانخراط في العمل المستقل، دعمًا للاقتصاد الجديد وريادة الأعمال بين الشباب.',0,40);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('initiatives','برنامج المحفزات الوظيفية للقطاع غير الربحي',
 'برنامج من وزارة الموارد البشرية لزيادة مساهمة القطاع غير الربحي في الناتج المحلي وخلق آلاف الفرص الوظيفية للشباب والشابات ضمن مسارات مهنية ذات أثر اجتماعي.',0,50);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('initiatives','برنامج الابتعاث السعودي لتطوير مواهب كرة القدم',
 'أطلقته وزارة الرياضة لتأهيل اللاعبين الشباب للانتقال إلى الأندية الأوروبية أو العودة إلى الدوري السعودي بخبرات احترافية.',0,60);

-- ---------------- إسهام القطاع غير الربحي — مركز مرشاد ----------------
INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","FIGURE_VALUE","FIGURE_LABEL","IS_FEATURED","DISPLAY_ORDER") VALUES
('nonprofit','مركز مرشاد لبحوث ودراسات الشباب',
 'مركز بحثي متخصص في قضايا الشباب، أنجز خلال 2025 أربعة عشر مشروعًا ودراسة تشمل منهجية البحث العلمي في قضايا الشباب، وتحليل الجهود المبذولة في منظومة الشباب، وفرص التكامل مع برامج رؤية 2030، والتوجهات المؤثرة مستقبلًا، وتصميم المدن الصديقة للشباب، وسن المسؤولية، وطبقات أجيال الشباب، والقيم الأساسية، ومؤشر قضايا الشباب، وموقع المملكة في مؤشرات التنمية الشبابية العالمية.',
 '14','مشروعًا ودراسة في 2025',1,10);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('nonprofit','منصة بيانات الشباب التشاركية',
 'منصة تقنية تجمع بيانات شاملة وموحّدة لمنظومة الشباب في المملكة، تخدم المعنيين والمهتمين بالشأن الشبابي — أحد مشاريع مركز مرشاد.',0,20);

INSERT INTO "YOUTH_ACHIEVEMENTS" ("CATEGORY","TITLE","SUMMARY","IS_FEATURED","DISPLAY_ORDER") VALUES
('nonprofit','مؤشر قضايا الشباب',
 'مشروع يسعى إلى بناء أداة لتحليل ورصد القضايا ذات الأولوية للشباب، ويوفّر بيانات دقيقة تساعد في صياغة السياسات واتخاذ القرارات النوعية.',0,30);

COMMIT;
