-- ============================================================
-- منظومة تحليلات الزيارات والبحث — الجداول (سكيمة DATA_CENTER)
-- شغّله مرة واحدة في SQL Workshop → SQL Scripts
-- ============================================================

-- 1) زيارات الصفحات
CREATE TABLE "VISITS" (
  "ID"            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "VISITOR_ID"    VARCHAR2(64),                 -- معرّف مجهول ثابت للجهاز (لحساب الزوّار الفريدين)
  "USER_ID"       NUMBER,                       -- إن كان مسجّلاً (NULL = زائر غير مسجّل)
  "IS_REGISTERED" NUMBER(1) DEFAULT 0,
  "PAGE_PATH"     VARCHAR2(500),                -- المسار الكامل: /categories/books/123
  "PAGE_PATTERN"  VARCHAR2(200),                -- النمط للتجميع: /categories/[slug]/[id]
  "PAGE_TITLE"    VARCHAR2(300),
  "REFERRER"      VARCHAR2(500),
  "COUNTRY_CODE"  VARCHAR2(2),                  -- SA
  "REGION_CODE"   VARCHAR2(10),                 -- 01
  "REGION_NAME"   VARCHAR2(100),                -- الرياض
  "CITY"          VARCHAR2(100),
  "DEVICE_TYPE"   VARCHAR2(20),                 -- mobile | desktop | tablet
  "BROWSER"       VARCHAR2(50),
  "OS"            VARCHAR2(50),
  "SESSION_KEY"   VARCHAR2(64),                 -- لتجميع زيارات الجلسة الواحدة
  "VISITED_AT"    TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT "VISITS_PK" PRIMARY KEY ("ID")
);

CREATE INDEX "VISITS_AT_IX"      ON "VISITS" ("VISITED_AT");
CREATE INDEX "VISITS_PATH_IX"    ON "VISITS" ("PAGE_PATH");
CREATE INDEX "VISITS_PATTERN_IX" ON "VISITS" ("PAGE_PATTERN");
CREATE INDEX "VISITS_USER_IX"    ON "VISITS" ("USER_ID");
CREATE INDEX "VISITS_GEO_IX"     ON "VISITS" ("COUNTRY_CODE","REGION_CODE");

-- 2) سجل عمليات البحث
CREATE TABLE "SEARCH_LOG" (
  "ID"           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "VISITOR_ID"   VARCHAR2(64),
  "USER_ID"      NUMBER,
  "TERM"         VARCHAR2(400),                 -- الكلمة كما كتبها المستخدم
  "TERM_NORM"    VARCHAR2(400),                 -- منظّفة (lower/trim) للتجميع الدقيق
  "RESULTS_CNT"  NUMBER,                        -- عدد النتائج (0 = بحث بلا نتائج!)
  "PAGE_PATH"    VARCHAR2(500),
  "COUNTRY_CODE" VARCHAR2(2),
  "REGION_NAME"  VARCHAR2(100),
  "SEARCHED_AT"  TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT "SEARCH_LOG_PK" PRIMARY KEY ("ID")
);

CREATE INDEX "SEARCH_AT_IX"   ON "SEARCH_LOG" ("SEARCHED_AT");
CREATE INDEX "SEARCH_TERM_IX" ON "SEARCH_LOG" ("TERM_NORM");

-- 3) مرجع مناطق السعودية (رمز ISO 3166-2:SA → الاسم العربي)
CREATE TABLE "GEO_SA_REGIONS" (
  "CODE"    VARCHAR2(10) NOT NULL,
  "NAME_AR" VARCHAR2(100) NOT NULL,
  CONSTRAINT "GEO_SA_REGIONS_PK" PRIMARY KEY ("CODE")
);

INSERT INTO "GEO_SA_REGIONS" ("CODE","NAME_AR") VALUES ('01','الرياض');
INSERT INTO "GEO_SA_REGIONS" ("CODE","NAME_AR") VALUES ('02','مكة المكرمة');
INSERT INTO "GEO_SA_REGIONS" ("CODE","NAME_AR") VALUES ('03','المدينة المنورة');
INSERT INTO "GEO_SA_REGIONS" ("CODE","NAME_AR") VALUES ('04','المنطقة الشرقية');
INSERT INTO "GEO_SA_REGIONS" ("CODE","NAME_AR") VALUES ('05','القصيم');
INSERT INTO "GEO_SA_REGIONS" ("CODE","NAME_AR") VALUES ('06','حائل');
INSERT INTO "GEO_SA_REGIONS" ("CODE","NAME_AR") VALUES ('07','تبوك');
INSERT INTO "GEO_SA_REGIONS" ("CODE","NAME_AR") VALUES ('08','الحدود الشمالية');
INSERT INTO "GEO_SA_REGIONS" ("CODE","NAME_AR") VALUES ('09','جازان');
INSERT INTO "GEO_SA_REGIONS" ("CODE","NAME_AR") VALUES ('10','نجران');
INSERT INTO "GEO_SA_REGIONS" ("CODE","NAME_AR") VALUES ('11','الباحة');
INSERT INTO "GEO_SA_REGIONS" ("CODE","NAME_AR") VALUES ('12','الجوف');
INSERT INTO "GEO_SA_REGIONS" ("CODE","NAME_AR") VALUES ('14','عسير');
COMMIT;
