-- ============================================================
-- منظومة النشرة البريدية — جداول قاعدة البيانات (سكيمة DATA_CENTER)
-- يُشغَّل مرة واحدة في SQL Workshop
-- ============================================================

-- 1) المشتركون
CREATE TABLE "NEWSLETTER_SUBSCRIBERS" (
  "ID"              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "EMAIL"           VARCHAR2(320) NOT NULL,
  "FULL_NAME"       VARCHAR2(255),
  "USER_ID"         NUMBER,                          -- إن كان مستخدماً مسجّلاً
  "STATUS"          VARCHAR2(20)  DEFAULT 'active',  -- active | unsubscribed
  "CONFIRM_TOKEN"   VARCHAR2(64),                    -- لرابط إلغاء الاشتراك
  "SOURCE"          VARCHAR2(50)  DEFAULT 'website', -- website | admin | import
  "SUBSCRIBED_AT"   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  "UNSUBSCRIBED_AT" TIMESTAMP,
  CONSTRAINT "NL_SUBS_PK" PRIMARY KEY ("ID"),
  CONSTRAINT "NL_SUBS_EMAIL_UK" UNIQUE ("EMAIL")
);

-- 2) النشرات / الحملات
CREATE TABLE "NEWSLETTER_CAMPAIGNS" (
  "ID"          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "SUBJECT"     VARCHAR2(500) NOT NULL,
  "BODY_HTML"   CLOB,
  "STATUS"      VARCHAR2(20) DEFAULT 'draft',  -- draft | sending | sent
  "RECIPIENTS"  NUMBER DEFAULT 0,
  "SENT_COUNT"  NUMBER DEFAULT 0,
  "FAIL_COUNT"  NUMBER DEFAULT 0,
  "CREATED_AT"  TIMESTAMP DEFAULT SYSTIMESTAMP,
  "SENT_AT"     TIMESTAMP,
  "CREATED_BY"  VARCHAR2(255),
  CONSTRAINT "NL_CAMP_PK" PRIMARY KEY ("ID")
);

-- 3) سجل الإرسال
CREATE TABLE "NEWSLETTER_SEND_LOG" (
  "ID"          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "CAMPAIGN_ID" NUMBER,
  "EMAIL"       VARCHAR2(320),
  "STATUS"      VARCHAR2(20),   -- sent | failed
  "ERROR_MSG"   VARCHAR2(2000),
  "SENT_AT"     TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT "NL_LOG_PK" PRIMARY KEY ("ID")
);

-- 4) إعدادات الإرسال عبر Microsoft 365 (صف واحد)
CREATE TABLE "NEWSLETTER_CONFIG" (
  "ID"            NUMBER DEFAULT 1 NOT NULL,
  "TENANT_ID"     VARCHAR2(100),
  "CLIENT_ID"     VARCHAR2(100),
  "CLIENT_SECRET" VARCHAR2(300),
  "SENDER_EMAIL"  VARCHAR2(320),
  "FROM_NAME"     VARCHAR2(200) DEFAULT 'منصة بيانات الشباب',
  "SITE_URL"      VARCHAR2(300) DEFAULT 'https://youth-data-platform.vercel.app',
  "UNSUB_BASE"    VARCHAR2(300) DEFAULT 'https://youthdata.maxapex.net/ords/data_center/account/v1/newsletter/unsubscribe/',
  CONSTRAINT "NL_CFG_PK" PRIMARY KEY ("ID")
);

INSERT INTO "NEWSLETTER_CONFIG" ("ID") VALUES (1);
COMMIT;

CREATE INDEX "NL_SUBS_STATUS_IX" ON "NEWSLETTER_SUBSCRIBERS" ("STATUS");
CREATE INDEX "NL_LOG_CAMP_IX"    ON "NEWSLETTER_SEND_LOG" ("CAMPAIGN_ID");
