-- ============================================================
-- منظومة الاستبيانات — قاعدة البيانات (سكيمة DATA_CENTER)
-- م1: 6 جداول أساسية. يُشغَّل مرة واحدة في SQL Workshop → SQL Scripts
-- ============================================================

-- 1) الاستبيان
CREATE TABLE "SURVEYS" (
  "ID"             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "SLUG"           VARCHAR2(80),                    -- للرابط: /surveys/:slug
  "TITLE"          VARCHAR2(300) NOT NULL,
  "DESCRIPTION"    VARCHAR2(4000),
  "INTRO_TEXT"     VARCHAR2(2000),                  -- نص ترحيبي أعلى الاستبيان
  "THANKS_TEXT"    VARCHAR2(2000),                  -- رسالة الشكر بعد الإرسال
  "STATUS"         VARCHAR2(20) DEFAULT 'draft',    -- draft|pending|approved|published|closed|rejected
  "REQUIRE_LOGIN"  NUMBER(1) DEFAULT 0,             -- 1 = يتطلب تسجيل دخول للتعبئة
  "ALLOW_MULTIPLE" NUMBER(1) DEFAULT 0,             -- 1 = يُسمح بعدة ردود لكل بريد
  "COLLECT_EMAIL"  NUMBER(1) DEFAULT 1,             -- 1 = البريد إلزامي (كنماذج Google)
  "SHOW_ON_HOME"   NUMBER(1) DEFAULT 0,             -- 1 = يظهر في قسم الصفحة الرئيسية
  "SHOW_ANALYTICS" NUMBER(1) DEFAULT 0,             -- 1 = تظهر تحليلاته في صفحة تحليلات الاستبيانات
  "COVER_COLOR"    VARCHAR2(20) DEFAULT '#1e2a52',
  "COVER_ICON"     VARCHAR2(60) DEFAULT 'ClipboardList',
  "CLOSES_AT"      TIMESTAMP,                       -- تاريخ إغلاق اختياري
  "RESPONSE_COUNT" NUMBER DEFAULT 0,                -- كاش عدد الردود
  "CREATED_BY"     VARCHAR2(255),
  "CREATED_AT"     TIMESTAMP DEFAULT SYSTIMESTAMP,
  "SUBMITTED_AT"   TIMESTAMP,                       -- وقت طلب الاعتماد
  "APPROVED_BY"    VARCHAR2(255),
  "APPROVED_AT"    TIMESTAMP,
  "REJECT_REASON"  VARCHAR2(1000),
  "PUBLISHED_AT"   TIMESTAMP,
  CONSTRAINT "SURVEYS_PK" PRIMARY KEY ("ID"),
  CONSTRAINT "SURVEYS_SLUG_UK" UNIQUE ("SLUG"),
  CONSTRAINT "SURVEYS_STATUS_CK" CHECK ("STATUS" IN
    ('draft','pending','approved','published','closed','rejected'))
);

-- 2) الأسئلة
CREATE TABLE "SURVEY_QUESTIONS" (
  "ID"            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "SURVEY_ID"     NUMBER NOT NULL,
  "QTYPE"         VARCHAR2(20) NOT NULL,            -- انظر الأنواع أدناه
  "QTEXT"         VARCHAR2(1000) NOT NULL,
  "QDESC"         VARCHAR2(1000),                   -- وصف/تلميح تحت السؤال
  "IS_REQUIRED"   NUMBER(1) DEFAULT 0,
  "DISPLAY_ORDER" NUMBER DEFAULT 100,
  "PUBLISH_STAT"  NUMBER(1) DEFAULT 0,              -- 1 = تُنشر إحصائيته في المنصة
  "SETTINGS"      VARCHAR2(2000),                   -- JSON للإعدادات الخاصة بالنوع
  CONSTRAINT "SQ_PK" PRIMARY KEY ("ID"),
  CONSTRAINT "SQ_SURVEY_FK" FOREIGN KEY ("SURVEY_ID") REFERENCES "SURVEYS"("ID") ON DELETE CASCADE,
  CONSTRAINT "SQ_TYPE_CK" CHECK ("QTYPE" IN
    ('single','multiple','dropdown','short_text','long_text','number',
     'date','rating','scale','grid','yesno','email','phone'))
);
-- الأنواع: single=اختيار واحد · multiple=اختيار متعدد · dropdown=قائمة منسدلة
--          short_text=نص قصير · long_text=نص طويل · number=رقم · date=تاريخ
--          rating=تقييم نجوم · scale=مقياس خطي · grid=شبكة · yesno=نعم/لا
--          email=بريد · phone=هاتف
-- SETTINGS أمثلة: {"max":5} للتقييم · {"min":1,"max":10} للمقياس
--                 {"rows":["أ","ب"],"cols":["ممتاز","جيد"]} للشبكة · {"placeholder":"..."}

-- 3) خيارات الأسئلة (single/multiple/dropdown)
CREATE TABLE "SURVEY_OPTIONS" (
  "ID"            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "QUESTION_ID"   NUMBER NOT NULL,
  "OPT_TEXT"      VARCHAR2(500) NOT NULL,
  "DISPLAY_ORDER" NUMBER DEFAULT 100,
  CONSTRAINT "SO_PK" PRIMARY KEY ("ID"),
  CONSTRAINT "SO_Q_FK" FOREIGN KEY ("QUESTION_ID") REFERENCES "SURVEY_QUESTIONS"("ID") ON DELETE CASCADE
);

-- 4) المنطق الشرطي: أظهر/أخفِ سؤالاً بناءً على إجابة سؤال آخر
CREATE TABLE "SURVEY_CONDITIONS" (
  "ID"            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "SURVEY_ID"     NUMBER NOT NULL,
  "TARGET_Q"      NUMBER NOT NULL,                  -- السؤال المتأثّر
  "SOURCE_Q"      NUMBER NOT NULL,                  -- السؤال المُطلِق
  "OPERATOR"      VARCHAR2(15) DEFAULT 'equals',    -- equals|not_equals|contains|gt|lt
  "MATCH_VALUE"   VARCHAR2(500),
  "ACTION"        VARCHAR2(6) DEFAULT 'show',       -- show|hide
  CONSTRAINT "SC_PK" PRIMARY KEY ("ID"),
  CONSTRAINT "SC_SURVEY_FK" FOREIGN KEY ("SURVEY_ID") REFERENCES "SURVEYS"("ID") ON DELETE CASCADE
);

-- 5) جلسة الرد
CREATE TABLE "SURVEY_RESPONSES" (
  "ID"            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "SURVEY_ID"     NUMBER NOT NULL,
  "USER_ID"       NUMBER,                           -- إن كان مسجّلاً
  "EMAIL"         VARCHAR2(320),
  "RESPONDENT"    VARCHAR2(255),                    -- اسم اختياري
  "COUNTRY"       VARCHAR2(4),
  "REGION"        VARCHAR2(60),
  "CITY"          VARCHAR2(120),
  "IS_COMPLETE"   NUMBER(1) DEFAULT 1,
  "SUBMITTED_AT"  TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT "SR_PK" PRIMARY KEY ("ID"),
  CONSTRAINT "SR_SURVEY_FK" FOREIGN KEY ("SURVEY_ID") REFERENCES "SURVEYS"("ID") ON DELETE CASCADE
);

-- 6) إجابات الأسئلة (صف لكل سؤال؛ ولكل خيار مُختار في الاختيار المتعدد)
CREATE TABLE "SURVEY_ANSWERS" (
  "ID"            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "RESPONSE_ID"   NUMBER NOT NULL,
  "QUESTION_ID"   NUMBER NOT NULL,
  "OPTION_ID"     NUMBER,                           -- لأسئلة الاختيار
  "ANSWER_TEXT"   VARCHAR2(4000),                   -- للنصوص/الشبكة (JSON)
  "ANSWER_NUMBER" NUMBER,                           -- للرقم/التقييم/المقياس
  CONSTRAINT "SA_PK" PRIMARY KEY ("ID"),
  CONSTRAINT "SA_RESP_FK" FOREIGN KEY ("RESPONSE_ID") REFERENCES "SURVEY_RESPONSES"("ID") ON DELETE CASCADE,
  CONSTRAINT "SA_Q_FK" FOREIGN KEY ("QUESTION_ID") REFERENCES "SURVEY_QUESTIONS"("ID")
);

-- الفهارس
CREATE INDEX "SQ_SURVEY_IX"   ON "SURVEY_QUESTIONS" ("SURVEY_ID","DISPLAY_ORDER");
CREATE INDEX "SO_Q_IX"        ON "SURVEY_OPTIONS" ("QUESTION_ID","DISPLAY_ORDER");
CREATE INDEX "SR_SURVEY_IX"   ON "SURVEY_RESPONSES" ("SURVEY_ID","SUBMITTED_AT");
CREATE INDEX "SR_EMAIL_IX"    ON "SURVEY_RESPONSES" ("SURVEY_ID","EMAIL");
CREATE INDEX "SA_RESP_IX"     ON "SURVEY_ANSWERS" ("RESPONSE_ID");
CREATE INDEX "SA_Q_IX"        ON "SURVEY_ANSWERS" ("QUESTION_ID","OPTION_ID");

-- ============ استبيان تجريبي للاختبار الفوري ============
DECLARE
  s NUMBER; q1 NUMBER; q2 NUMBER; q3 NUMBER;
BEGIN
  INSERT INTO "SURVEYS" (SLUG,TITLE,DESCRIPTION,INTRO_TEXT,THANKS_TEXT,STATUS,
                         COLLECT_EMAIL,SHOW_ON_HOME,SHOW_ANALYTICS,CREATED_BY,PUBLISHED_AT)
  VALUES ('youth-priorities','أولويات الشباب السعودي',
          'استبيان قصير لقياس أولويات الشباب واهتماماتهم.',
          'رأيك يهمّنا — دقيقتان تكفيان لإكمال الاستبيان.',
          'شكراً لمشاركتك! ستُسهم إجاباتك في فهم أولويات الشباب.',
          'published',1,1,1,'admin',SYSTIMESTAMP)
  RETURNING "ID" INTO s;

  INSERT INTO "SURVEY_QUESTIONS" (SURVEY_ID,QTYPE,QTEXT,IS_REQUIRED,DISPLAY_ORDER,PUBLISH_STAT)
  VALUES (s,'single','ما أهم مجال تراه أولوية للشباب؟',1,10,1) RETURNING "ID" INTO q1;
  INSERT INTO "SURVEY_OPTIONS" (QUESTION_ID,OPT_TEXT,DISPLAY_ORDER) VALUES (q1,'التعليم والتدريب',10);
  INSERT INTO "SURVEY_OPTIONS" (QUESTION_ID,OPT_TEXT,DISPLAY_ORDER) VALUES (q1,'التوظيف وريادة الأعمال',20);
  INSERT INTO "SURVEY_OPTIONS" (QUESTION_ID,OPT_TEXT,DISPLAY_ORDER) VALUES (q1,'الصحة النفسية والاجتماعية',30);
  INSERT INTO "SURVEY_OPTIONS" (QUESTION_ID,OPT_TEXT,DISPLAY_ORDER) VALUES (q1,'التقنية والذكاء الاصطناعي',40);
  INSERT INTO "SURVEY_OPTIONS" (QUESTION_ID,OPT_TEXT,DISPLAY_ORDER) VALUES (q1,'الترفيه والرياضة',50);

  INSERT INTO "SURVEY_QUESTIONS" (SURVEY_ID,QTYPE,QTEXT,IS_REQUIRED,DISPLAY_ORDER,PUBLISH_STAT,SETTINGS)
  VALUES (s,'scale','ما مدى رضاك عن الفرص المتاحة للشباب حالياً؟',1,20,1,'{"min":1,"max":10}') RETURNING "ID" INTO q2;

  INSERT INTO "SURVEY_QUESTIONS" (SURVEY_ID,QTYPE,QTEXT,IS_REQUIRED,DISPLAY_ORDER,PUBLISH_STAT)
  VALUES (s,'multiple','أي القنوات تفضّل لتلقّي الفرص والمبادرات؟',0,30,1) RETURNING "ID" INTO q3;
  INSERT INTO "SURVEY_OPTIONS" (QUESTION_ID,OPT_TEXT,DISPLAY_ORDER) VALUES (q3,'وسائل التواصل الاجتماعي',10);
  INSERT INTO "SURVEY_OPTIONS" (QUESTION_ID,OPT_TEXT,DISPLAY_ORDER) VALUES (q3,'البريد الإلكتروني',20);
  INSERT INTO "SURVEY_OPTIONS" (QUESTION_ID,OPT_TEXT,DISPLAY_ORDER) VALUES (q3,'المنصات الحكومية',30);
  INSERT INTO "SURVEY_OPTIONS" (QUESTION_ID,OPT_TEXT,DISPLAY_ORDER) VALUES (q3,'الجامعات والمدارس',40);

  INSERT INTO "SURVEY_QUESTIONS" (SURVEY_ID,QTYPE,QTEXT,IS_REQUIRED,DISPLAY_ORDER,PUBLISH_STAT,SETTINGS)
  VALUES (s,'long_text','ما اقتراحك لتحسين الخدمات المقدّمة للشباب؟',0,40,0,'{"placeholder":"اكتب اقتراحك هنا..."}');

  COMMIT;
END;
/
